# Generated by Django 4.1.1 on 2022-09-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
