# Generated by Django 4.1.1 on 2022-09-16 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, default=str, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categories'),
        ),
    ]
