# Generated by Django 4.1.1 on 2022-09-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, default='White Tea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categories'),
        ),
    ]
