# Generated by Django 4.1.1 on 2022-09-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_categories_id_alter_categories_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
